name: crnn
base: ['config/image_dataset.yaml']
arch:
  type: crnnModel
  args:
    binarization:
      type: ResNetFPN
      args:
        backbone: resnet18
        pretrained: true
    feature_extraction:
      type: DenseNet
    sequence_model:
      type: RNN
      args:
        hidden_size: 512
        num_layers: 1
    prediction:
      type: CTC
optimizer:
  type: Adam
  args:
    lr: 0.001
lr_scheduler:
  type: StepLR
  args:
    step_size: 2
    gamma: 0.1
trainer:
  seed: 2
  gpus:
    - 0
  epochs: 100
  display_interval: 10
  resume_checkpoint: E:\zj\code\crnn.pytorch\output\crnn_ResNetFPN_DenseNet_RNN_CTC\checkpoint/model_latest.params
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  alphabet: alphabet.npy
  train:
    dataset:
      type: ImageDataset # 数据集类型
      args:
        data_path:
          - - E:/zj/dataset/train.txt
        data_ratio:
          - 1.0
        img_mode: RGB
    loader:
      batch_size: 16
      shuffle: true
      pin_memory: false
      num_workers: 6
  validate:
    dataset:
      type: ImageDataset
      args:
        data_path: # [文件，文件]，每个文件格式为 img_path \t gt
          - E:/zj/dataset/train.txt
        img_mode: RGB
    loader:
      batch_size: 4
      shuffle: true
      pin_memory: false
      num_workers: 6