name: crnn_lmdb_DWBlock
base: ['config/image_dataset.yaml']
arch:
  type: crnnModel
  args:
    binarization:
      type: None
    feature_extraction:
      type: ResNet
      args:
        conv_type: DWBlock
    sequence_model:
      type: RNN
      args:
        hidden_size: 256
    prediction:
      type: CTC
optimizer:
  type: Adam
  args:
    lr: 0.001
lr_scheduler:
  type: StepLR
  args:
    step_size: 30
    gamma: 0.1
trainer:
  seed: 2
  gpus:
    - 2
  epochs: 10
  display_interval: 100
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: false
dataset:
  alphabet: dict.txt
  train:
    dataset:
      type: LmdbDataset # 数据集类型
      args:
        data_path:
          - /data1/ocr/dataset/test_crn/lmdb/train
        data_ratio:
          - 1.0
        img_mode: RGB
    loader:
      batch_size: 128
      shuffle: true
      pin_memory: false
      num_workers: 16
  validate:
    dataset:
      type: LmdbDataset
      args:
        data_path:
          - /data1/ocr/dataset/test_crn/lmdb/val
        img_mode: RGB
    loader:
      batch_size: 64
      shuffle: true
      pin_memory: false
      num_workers: 6