name: crnn
base: ['config/image_dataset.yaml']
arch:
  type: crnnModel
  args:
    transformation:
      type: None
      args:
        input_size: [32,320]
        num_fiducial: 20
    feature_extraction:
      type: VGG
      args:
        conv_type: BasicConv
    sequence_model:
      type: RNN
      args:
        hidden_size: 256
    prediction:
      type: CTC
optimizer:
  type: Adam
  args:
    lr: 0.001
lr_scheduler:
  type: StepLR
  args:
    step_size: 30
    gamma: 0.1
trainer:
  seed: 2
  gpus:
    - 0
  epochs: 10
  display_interval: 10
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: false
dataset:
  alphabet: dict.txt
  train:
    dataset:
      type: ImageDataset # 数据集类型
      args:
        data_path:
          - - E:\zj\dataset\test_crnn\train.txt
        data_ratio:
          - 1.0
        img_mode: RGB
    loader:
      batch_size: 16
      shuffle: true
      pin_memory: false
      num_workers: 6
  validate:
    dataset:
      type: ImageDataset
      args:
        data_path: # [文件，文件]，每个文件格式为 img_path \t gt
          - E:\zj\dataset\test_crnn\val.txt
        img_mode: RGB
    loader:
      batch_size: 4
      shuffle: true
      pin_memory: false
      num_workers: 6