name: crnn
base: ['config/image_dataset.yaml']
arch:
  type: Model
  trans:
    type: None # TPS or None
    input_size: [32,320]
    num_fiducial: 20
  backbone:
    type: VGG
    conv_type: BasicConv
  neck:
    type: RNNDecoder # RNNDecoder or CNNDecoder or Reshape, Reshape 表示不使用decode
    hidden_size: 256
  head:
    type: CTC # CTC or Attention, Attention 必须和 RNNDecoder一起使用
loss:
  type: CTCLoss
  blank: 0

optimizer:
  type: Adam # Adagrad
  args:
    lr: 0.001
lr_scheduler:
  type: StepLR
  args:
    step_size: 30
    gamma: 0.1
trainer:
  seed: 2
  gpus:
    - 0
  epochs: 10
  log_iter: 10
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  alphabet: digit.txt
  train:
    dataset:
      type: ImageDataset # 数据集类型
      args:
        data_path:
          - - path/train.txt
        data_ratio:
          - 1.0
        pre_processes: # 数据的预处理过程，包含augment和预处理
          #          - type: IaaAugment # 使用imgaug进行变换
          #          - type: RandomAug # 进行变换扭曲变换
          - type: Resize
            args:
              img_h: 32
              img_w: 120
              pad: true
              random_crop: false
        transforms: # 对图片进行的变换方式
          #          - type: ColorJitter
          #            args:
          #              brightness: 0.5
          - type: ToTensor
            args: {}
        #          - type: Normalize
        #            args:
        #              mean: [0.485, 0.456, 0.406]
        #              std: [0.229, 0.224, 0.225]
        img_mode: RGB
        ignore_chinese_punctuation: true
        remove_blank: true
    loader:
      batch_size: 16
      shuffle: true
      pin_memory: false
      num_workers: 6
  validate:
    dataset:
      type: ImageDataset
      args:
        data_path: # [文件，文件]，每个文件格式为 img_path \t gt
          - path/val.txt
        pre_processes:
          - type: Resize
            args:
              img_h: 32
              img_w: 120
              pad: true
              random_crop: false
        transforms:
          - type: ToTensor
            args: {}
        #          - type: Normalize
        #            args:
        #              mean: [0.485, 0.456, 0.406]
        #              std: [0.229, 0.224, 0.225]
        img_mode: RGB
        ignore_chinese_punctuation: true
        remove_blank: true
    loader:
      batch_size: 4
      shuffle: true
      pin_memory: false
      num_workers: 6